# Generated by Django 5.2.5 on 2025-12-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_post_image_remove_post_video_post_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(related_name='hashtag_post', to='myapp.hashtag'),
        ),
    ]
