# Generated by Django 5.2.5 on 2025-12-26 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_hashtag_post_post_hashtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlike',
            name='like',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='like',
        ),
    ]
