# Generated by Django 5.2.5 on 2025-12-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_postlike_post_alter_postlike_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
