# Generated by Django 5.2.5 on 2025-12-28 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_postlike_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlike',
            name='like',
        ),
    ]
